;;================================================
;; clyax.lisp
;;
;; written by R.Ueda (garaemon)
;;================================================

(defpackage :xlib
  (:use #:common-lisp #:cffi #:chimi)
  (:export
   #:create-window
   #:create-simple-window
   #:match-visual-info
   #:store-name
   #:set-window-background
   #:set-background
   #:set-foreground
   #:set-fill-style
   #:select-input
   #:create-size-hints
   #:set-normal-hints
   #:set-standard-properties
   #:create-colormap
   #:clear-window
   #:map-window
   #:unmap-window
   #:create-gc
   #:create-image
   #:put-image
   #:move-window
   #:resize-window
   #:default-visual
   #:create-set-window-attributes
   #:new-event
   #:open-display
   #:default-root-window
   #:default-screen
   #:sync #:flush
   #:events-queued
   #:next-event
   #:free
   #:event-constant->event-key
   ;; xevent accessors
   #:EVENT-TYPE
   #:EVENT-XANY
   #:EVENT-XKEY
   #:EVENT-XBUTTON
   #:EVENT-XMOTION
   #:EVENT-XCROSSING
   #:EVENT-XFOCUS
   #:EVENT-XEXPOSE
   #:EVENT-XGRAPHICSEXPOSE
   #:EVENT-XNOEXPOSE
   #:EVENT-XVISIBILITY
   #:EVENT-XCREATEWINDOW
   #:EVENT-XDESTROYWINDOW
   #:EVENT-XUNMAP
   #:EVENT-XMAP
   #:EVENT-XMAPREQUEST
   #:EVENT-XREPARENT
   #:EVENT-XCONFIGURE
   #:EVENT-XGRAVITY
   #:EVENT-XRESIZEREQUEST
   #:EVENT-XCONFIGUREREQUEST
   #:EVENT-XCIRCULATE
   #:EVENT-XCIRCULATEREQUEST
   #:EVENT-XPROPERTY
   #:EVENT-XSELECTIONCLEAR
   #:EVENT-XSELECTIONREQUEST
   #:EVENT-XSELECTION
   #:EVENT-XCOLORMAP
   #:EVENT-XCLIENT
   #:EVENT-XMAPPING
   #:EVENT-XERROR
   #:EVENT-XKEYMAP
   #:EVENT-PAD
   #:VISUAL-INFO-VISUAL
   #:VISUAL-INFO-VISUALID
   #:VISUAL-INFO-SCREEN
   #:VISUAL-INFO-DEPTH
   #:VISUAL-INFO-CLASS
   #:VISUAL-INFO-RED_MASK
   #:VISUAL-INFO-GREEN_MASK
   #:VISUAL-INFO-BLUE_MASK
   #:VISUAL-INFO-COLORMAP_SIZE
   #:VISUAL-INFO-BITS_PER_RGB
   #:SET-WINDOW-ATTRIBUTES-BACKGROUND_PIXMAP
   #:SET-WINDOW-ATTRIBUTES-BACKGROUND_PIXEL
   #:SET-WINDOW-ATTRIBUTES-BORDER_PIXMAP
   #:SET-WINDOW-ATTRIBUTES-BORDER_PIXEL
   #:SET-WINDOW-ATTRIBUTES-BIT_GRAVITY
   #:SET-WINDOW-ATTRIBUTES-WIN_GRAVITY
   #:SET-WINDOW-ATTRIBUTES-BACKING_STORE
   #:SET-WINDOW-ATTRIBUTES-BACKING_PLANES
   #:SET-WINDOW-ATTRIBUTES-BACKING_PIXEL
   #:SET-WINDOW-ATTRIBUTES-SAVE_UNDER
   #:SET-WINDOW-ATTRIBUTES-EVENT_MASK
   #:SET-WINDOW-ATTRIBUTES-DO_NOT_PROPAGATE_MASK
   #:SET-WINDOW-ATTRIBUTES-OVERRIDE_REDIRECT
   #:SET-WINDOW-ATTRIBUTES-COLORMAP
   #:SET-WINDOW-ATTRIBUTES-CURSOR
   ;; util
   #:event-case
   ;; constants
   #:+true+ #:+false+
   ;; events
   #:+key-press+ #:+key-release+
   #:+button-press+ #:+button-release+
   #:+motion-notify+ #:+enter-notify+
   #:+leave-notify+ #:+focus-in+
   #:+focus-out+ #:+keymap-notify+
   #:+expose+ #:+graphics-expose+
   #:+no-expose+ #:+visibility-notify+
   #:+create-notify+ #:+destroy-notify+
   #:+unmap-notify+ #:+map-notify+
   #:+map-request+ #:+reparent-notify+
   #:+configure-notify+ #:+configure-request+
   #:+gravity-notify+ #:+resize-request+
   #:+circulate-notify+ #:+circulate-request+
   #:+property-notify+ #:+selection-clear+
   #:+selection-request+ #:+selection-notify+
   #:+colormap-notify+ #:+client-message+
   #:+mapping-notify+ #:+generic-event+
   #:+last-event+
   ;; event mask
   #:+no-event-mask+
   #:+key-press-mask+
   #:+key-release-mask+
   #:+button-press-mask+
   #:+button-release-mask+
   #:+enter-window-mask+
   #:+leave-window-mask+
   #:+pointer-motion-mask+
   #:+resize-redirect-mask+
   #:+substructure-notify-mask+
   #:+substructure-redirect-mask+
   #:+focus-change-mask+
   #:+preperty-change-mask+
   #:+colormap-change-mask+
   #:+owner-grab-button-mask+
   #:+pointer-motion-hint-mask+
   #:+button1-motion-mask+
   #:+button2-motion-mask+
   #:+button3-motion-mask+
   #:+button4-motion-mask+
   #:+button5-motion-mask+
   #:+button-motion-mask+
   #:+keymap-state-mask+
   #:+exposure-mask+
   #:+visibility-change-mask+
   #:+structure-notify-mask+
   #:+cw-back-pixmap+
   #:+cw-back-pixel+
   #:+cw-border-pixmap+
   #:+cw-border-pixel+
   #:+cw-bit-gravity+
   #:+cw-win-gravity+
   #:+cw-backing-store+
   #:+cw-backing-planes+
   #:+cw-backing-pixel+
   #:+cw-override-redirect+
   #:+cw-save-under+
   #:+cw-event-mask+
   #:+cw-dont-propagate+
   #:+cw-colormap+
   #:+cw-cursor+
   #:+cw-x+
   #:+cw-y+
   #:+cw-width+
   #:+cw-height+
   #:+cw-border-width+
   #:+cw-sibling+
   #:+cw-stack-mode+
   #:+xy-bitmap+
   #:+xy-pixmap+
   #:+z-pixmap+
   #:+none+
   #:+alloc-none+
   #:+alloc-all+
   #:+input-output+
   #:+input-only+
   #:+static-gray+
   #:+Gray-Scale+
   #:+Static-Color+
   #:+Pseudo-Color+
   #:+True-Color+
   #:+Direct-Color+
   #:+US-Position+
   #:+US-Size+
   #:+P-Position+
   #:+P-Size+
   #:+P-Min-Size+
   #:+P-Max-Size+
   #:+P-Resize-Inc+
   #:+P-Aspect+
   #:+P-Base-Size+
   #:+P-Win-Gravity+
   #:+P-All-Hints+
   )
  )

(defpackage :gl
  (:use #:common-lisp #:cffi  #:chimi)
  (:export
   #:push-matrix
   #:pop-matrix
   #:push-attrib
   #:pop-attrib
   #:enable
   #:disable
   #:clear-color
   #:vertex-3f
   #:vertex-3d
   #:translate-f
   #:translate-d
   #:normal-3f
   #:normal-3d
   #:begin
   #:end
   #:color-3f
   #:color-3d
   #:tex-coord-2f
   #:tex-coord-2d
   #:gen-textures
   #:gen-lists
   #:new-list
   #:end-list
   #:depth-mask
   #:blend-func
   #:tex-parameter-i
   #:bind-texture
   #:tex-image-2d
   #:call-list
   #:tex-env-i
   #:pixel-store-i
   #:front-face
   #:cull-face
   #:shade-model
   #:viewport
   #:flush
   #:matrix-mode
   #:load-identity
   #:flush
   #:depth-func
   #:clear
   #:+version-1-1+
   #:+version-1-2+
   #:+version-1-3+
   #:+version-1-4+
   #:+version-1-5+
   #:+version-2-0+
   #:+version-2-1+
   #:+accum+
   #:+load+
   #:+return+
   #:+mult+
   #:+add+
   #:+never+
   #:+less+
   #:+equal+
   #:+lequal+
   #:+greater+
   #:+not-equal+
   #:+gequal+
   #:+always+
   #:+current-bit+
   #:+point-bit+
   #:+line-bit+
   #:+polygon-bit+
   #:+polygon-stipple-bit+
   #:+pixel-mode-bit+
   #:+lighting-bit+
   #:+fog-bit+
   #:+depth-buffer-bit+
   #:+accum-buffer-bit+
   #:+stencil-buffer-bit+
   #:+viewport-bit+
   #:+transform-bit+
   #:+enable-bit+
   #:+color-buffer-bit+
   #:+hint-bit+
   #:+eval-bit+
   #:+list-bit+
   #:+texture-bit+
   #:+scissor-bit+
   #:+all-attrib-bits+
   #:+points+
   #:+lines+
   #:+line-loop+
   #:+line-strip+
   #:+triangles+
   #:+triangle-strip+
   #:+triangle-fan+
   #:+quads+
   #:+quad-strip+
   #:+polygon+
   #:+zero+
   #:+one+
   #:+src-color+
   #:+one-minus-src-color+
   #:+src-alpha+
   #:+one-minus-src-alpha+
   #:+dst-alpha+
   #:+one-minus-dst-alpha+
   #:+dst-color+
   #:+one-minus-dst-color+
   #:+src-alpha-saturate+
   #:+true+
   #:+false+
   #:+clip-plane0+
   #:+clip-plane1+
   #:+clip-plane2+
   #:+clip-plane3+
   #:+clip-plane4+
   #:+clip-plane5+
   #:+byte+
   #:+unsigned-byte+
   #:+short+
   #:+unsigned-short+
   #:+int+
   #:+unsigned-int+
   #:+float+
   #:+2-bytes+
   #:+3-bytes+
   #:+4-bytes+
   #:+double+
   #:+none+
   #:+front-left+
   #:+front-right+
   #:+back-left+
   #:+back-right+
   #:+front+
   #:+back+
   #:+left+
   #:+right+
   #:+front-and-back+
   #:+aux0+
   #:+aux1+
   #:+aux2+
   #:+aux3+
   #:+no-error+
   #:+invalid-enum+
   #:+invalid-value+
   #:+invalid-operation+
   #:+stack-overflow+
   #:+stack-underflow+
   #:+out-of-memory+
   #:+2d+
   #:+3d+
   #:+3d-color+
   #:+3d-color-texture+
   #:+4d-color-texture+
   #:+pass-through-token+
   #:+point-token+
   #:+line-token+
   #:+polygon-token+
   #:+bitmap-token+
   #:+draw-pixel-token+
   #:+copy-pixel-token+
   #:+line-reset-token+
   #:+exp+
   #:+exp2+
   #:+cw+
   #:+ccw+
   #:+coeff+
   #:+order+
   #:+domain+
   #:+current-color+
   #:+current-index+
   #:+current-normal+
   #:+current-texture-coords+
   #:+current-raster-color+
   #:+current-raster-index+
   #:+current-raster-texture-coords+
   #:+current-raster-position+
   #:+current-raster-position-valid+
   #:+current-raster-distance+
   #:+point-smooth+
   #:+point-size+
   #:+point-size-range+
   #:+point-size-granularity+
   #:+line-smooth+
   #:+line-width+
   #:+line-width-range+
   #:+line-width-granularity+
   #:+line-stipple+
   #:+line-stipple-pattern+
   #:+line-stipple-repeat+
   #:+list-mode+
   #:+max-list-nesting+
   #:+list-base+
   #:+list-index+
   #:+polygon-mode+
   #:+polygon-smooth+
   #:+polygon-stipple+
   #:+edge-flag+
   #:+cull-face+
   #:+cull-face-mode+
   #:+front-face+
   #:+lighting+
   #:+light-model-local-viewer+
   #:+light-model-two-side+
   #:+light-model-ambient+
   #:+shade-model+
   #:+color-material-face+
   #:+color-material-parameter+
   #:+color-material+
   #:+fog+
   #:+fog-index+
   #:+fog-density+
   #:+fog-start+
   #:+fog-end+
   #:+fog-mode+
   #:+fog-color+
   #:+depth-range+
   #:+depth-test+
   #:+depth-writemask+
   #:+depth-clear-value+
   #:+depth-func+
   #:+accum-clear-value+
   #:+stencil-test+
   #:+stencil-clear-value+
   #:+stencil-func+
   #:+stencil-value-mask+
   #:+stencil-fail+
   #:+stencil-pass-depth-fail+
   #:+stencil-pass-depth-pass+
   #:+stencil-ref+
   #:+stencil-writemask+
   #:+matrix-mode+
   #:+normalize+
   #:+viewport+
   #:+modelview-stack-depth+
   #:+projection-stack-depth+
   #:+texture-stack-depth+
   #:+modelview-matrix+
   #:+projection-matrix+
   #:+texture-matrix+
   #:+attrib-stack-depth+
   #:+client-attrib-stack-depth+
   #:+alpha-test+
   #:+alpha-test-func+
   #:+alpha-test-ref+
   #:+dither+
   #:+blend-dst+
   #:+blend-src+
   #:+blend+
   #:+logic-op-mode+
   #:+index-logic-op+
   #:+color-logic-op+
   #:+aux-buffers+
   #:+draw-buffer+
   #:+read-buffer+
   #:+scissor-box+
   #:+scissor-test+
   #:+index-clear-value+
   #:+index-writemask+
   #:+color-clear-value+
   #:+color-writemask+
   #:+index-mode+
   #:+rgba-mode+
   #:+doublebuffer+
   #:+stereo+
   #:+render-mode+
   #:+perspective-correction-hint+
   #:+point-smooth-hint+
   #:+line-smooth-hint+
   #:+polygon-smooth-hint+
   #:+fog-hint+
   #:+texture-gen-s+
   #:+texture-gen-t+
   #:+texture-gen-r+
   #:+texture-gen-q+
   #:+pixel-map-i-to-i+
   #:+pixel-map-s-to-s+
   #:+pixel-map-i-to-r+
   #:+pixel-map-i-to-g+
   #:+pixel-map-i-to-b+
   #:+pixel-map-i-to-a+
   #:+pixel-map-r-to-r+
   #:+pixel-map-g-to-g+
   #:+pixel-map-b-to-b+
   #:+pixel-map-a-to-a+
   #:+pixel-map-i-to-i-size+
   #:+pixel-map-s-to-s-size+
   #:+pixel-map-i-to-r-size+
   #:+pixel-map-i-to-g-size+
   #:+pixel-map-i-to-b-size+
   #:+pixel-map-i-to-a-size+
   #:+pixel-map-r-to-r-size+
   #:+pixel-map-g-to-g-size+
   #:+pixel-map-b-to-b-size+
   #:+pixel-map-a-to-a-size+
   #:+unpack-swap-bytes+
   #:+unpack-lsb-first+
   #:+unpack-row-length+
   #:+unpack-skip-rows+
   #:+unpack-skip-pixels+
   #:+unpack-alignment+
   #:+pack-swap-bytes+
   #:+pack-lsb-first+
   #:+pack-row-length+
   #:+pack-skip-rows+
   #:+pack-skip-pixels+
   #:+pack-alignment+
   #:+map-color+
   #:+map-stencil+
   #:+index-shift+
   #:+index-offset+
   #:+red-scale+
   #:+red-bias+
   #:+zoom-x+
   #:+zoom-y+
   #:+green-scale+
   #:+green-bias+
   #:+blue-scale+
   #:+blue-bias+
   #:+alpha-scale+
   #:+alpha-bias+
   #:+depth-scale+
   #:+depth-bias+
   #:+max-eval-order+
   #:+max-lights+
   #:+max-clip-planes+
   #:+max-texture-size+
   #:+max-pixel-map-table+
   #:+max-attrib-stack-depth+
   #:+max-modelview-stack-depth+
   #:+max-name-stack-depth+
   #:+max-projection-stack-depth+
   #:+max-texture-stack-depth+
   #:+max-viewport-dims+
   #:+max-client-attrib-stack-depth+
   #:+subpixel-bits+
   #:+index-bits+
   #:+red-bits+
   #:+green-bits+
   #:+blue-bits+
   #:+alpha-bits+
   #:+depth-bits+
   #:+stencil-bits+
   #:+accum-red-bits+
   #:+accum-green-bits+
   #:+accum-blue-bits+
   #:+accum-alpha-bits+
   #:+name-stack-depth+
   #:+auto-normal+
   #:+map1-color-4+
   #:+map1-index+
   #:+map1-normal+
   #:+map1-texture-coord-1+
   #:+map1-texture-coord-2+
   #:+map1-texture-coord-3+
   #:+map1-texture-coord-4+
   #:+map1-vertex-3+
   #:+map1-vertex-4+
   #:+map2-color-4+
   #:+map2-index+
   #:+map2-normal+
   #:+map2-texture-coord-1+
   #:+map2-texture-coord-2+
   #:+map2-texture-coord-3+
   #:+map2-texture-coord-4+
   #:+map2-vertex-3+
   #:+map2-vertex-4+
   #:+map1-grid-domain+
   #:+map1-grid-segments+
   #:+map2-grid-domain+
   #:+map2-grid-segments+
   #:+texture-1d+
   #:+texture-2d+
   #:+feedback-buffer-pointer+
   #:+feedback-buffer-size+
   #:+feedback-buffer-type+
   #:+selection-buffer-pointer+
   #:+selection-buffer-size+
   #:+texture-width+
   #:+texture-height+
   #:+texture-internal-format+
   #:+texture-border-color+
   #:+texture-border+
   #:+dont-care+
   #:+fastest+
   #:+nicest+
   #:+light0+
   #:+light1+
   #:+light2+
   #:+light3+
   #:+light4+
   #:+light5+
   #:+light6+
   #:+light7+
   #:+ambient+
   #:+diffuse+
   #:+specular+
   #:+position+
   #:+spot-direction+
   #:+spot-exponent+
   #:+spot-cutoff+
   #:+constant-attenuation+
   #:+linear-attenuation+
   #:+quadratic-attenuation+
   #:+compile+
   #:+compile-and-execute+
   #:+clear+
   #:+and+
   #:+and-reverse+
   #:+copy+
   #:+and-inverted+
   #:+noop+
   #:+xor+
   #:+or+
   #:+nor+
   #:+equiv+
   #:+invert+
   #:+or-reverse+
   #:+copy-inverted+
   #:+or-inverted+
   #:+nand+
   #:+set+
   #:+emission+
   #:+shininess+
   #:+ambient-and-diffuse+
   #:+color-indexes+
   #:+modelview+
   #:+projection+
   #:+texture+
   #:+color+
   #:+depth+
   #:+stencil+
   #:+color-index+
   #:+stencil-index+
   #:+depth-component+
   #:+red+
   #:+green+
   #:+blue+
   #:+alpha+
   #:+rgb+
   #:+rgba+
   #:+luminance+
   #:+luminance-alpha+
   #:+bitmap+
   #:+point+
   #:+line+
   #:+fill+
   #:+render+
   #:+feedback+
   #:+select+
   #:+flat+
   #:+smooth+
   #:+keep+
   #:+replace+
   #:+incr+
   #:+decr+
   #:+vendor+
   #:+renderer+
   #:+version+
   #:+extensions+
   #:+s+
   #:+t+
   #:+r+
   #:+q+
   #:+modulate+
   #:+decal+
   #:+texture-env-mode+
   #:+texture-env-color+
   #:+texture-env+
   #:+eye-linear+
   #:+object-linear+
   #:+sphere-map+
   #:+texture-gen-mode+
   #:+object-plane+
   #:+eye-plane+
   #:+nearest+
   #:+linear+
   #:+nearest-mipmap-nearest+
   #:+linear-mipmap-nearest+
   #:+nearest-mipmap-linear+
   #:+linear-mipmap-linear+
   #:+texture-mag-filter+
   #:+texture-min-filter+
   #:+texture-wrap-s+
   #:+texture-wrap-t+
   #:+clamp+
   #:+repeat+
   #:+client-pixel-store-bit+
   #:+client-vertex-array-bit+
   #:+client-all-attrib-bits+
   #:+polygon-offset-factor+
   #:+polygon-offset-units+
   #:+polygon-offset-point+
   #:+polygon-offset-line+
   #:+polygon-offset-fill+
   #:+alpha4+
   #:+alpha8+
   #:+alpha12+
   #:+alpha16+
   #:+luminance4+
   #:+luminance8+
   #:+luminance12+
   #:+luminance16+
   #:+luminance4-alpha4+
   #:+luminance6-alpha2+
   #:+luminance8-alpha8+
   #:+luminance12-alpha4+
   #:+luminance12-alpha12+
   #:+luminance16-alpha16+
   #:+intensity+
   #:+intensity4+
   #:+intensity8+
   #:+intensity12+
   #:+intensity16+
   #:+r3-g3-b2+
   #:+rgb4+
   #:+rgb5+
   #:+rgb8+
   #:+rgb10+
   #:+rgb12+
   #:+rgb16+
   #:+rgba2+
   #:+rgba4+
   #:+rgb5-a1+
   #:+rgba8+
   #:+rgb10-a2+
   #:+rgba12+
   #:+rgba16+
   #:+texture-red-size+
   #:+texture-green-size+
   #:+texture-blue-size+
   #:+texture-alpha-size+
   #:+texture-luminance-size+
   #:+texture-intensity-size+
   #:+proxy-texture-1d+
   #:+proxy-texture-2d+
   #:+texture-priority+
   #:+texture-resident+
   #:+texture-binding-1d+
   #:+texture-binding-2d+
   #:+texture-binding-3d+
   #:+vertex-array+
   #:+normal-array+
   #:+color-array+
   #:+index-array+
   #:+texture-coord-array+
   #:+edge-flag-array+
   #:+vertex-array-size+
   #:+vertex-array-type+
   #:+vertex-array-stride+
   #:+normal-array-type+
   #:+normal-array-stride+
   #:+color-array-size+
   #:+color-array-type+
   #:+color-array-stride+
   #:+index-array-type+
   #:+index-array-stride+
   #:+texture-coord-array-size+
   #:+texture-coord-array-type+
   #:+texture-coord-array-stride+
   #:+edge-flag-array-stride+
   #:+vertex-array-pointer+
   #:+normal-array-pointer+
   #:+color-array-pointer+
   #:+index-array-pointer+
   #:+texture-coord-array-pointer+
   #:+edge-flag-array-pointer+
   #:+v2f+
   #:+v3f+
   #:+c4ub-v2f+
   #:+c4ub-v3f+
   #:+c3f-v3f+
   #:+n3f-v3f+
   #:+c4f-n3f-v3f+
   #:+t2f-v3f+
   #:+t4f-v4f+
   #:+t2f-c4ub-v3f+
   #:+t2f-c3f-v3f+
   #:+t2f-n3f-v3f+
   #:+t2f-c4f-n3f-v3f+
   #:+t4f-c4f-n3f-v4f+
   #:+bgr+
   #:+bgra+
   #:+constant-color+
   #:+one-minus-constant-color+
   #:+constant-alpha+
   #:+one-minus-constant-alpha+
   #:+blend-color+
   #:+func-add+
   #:+min+
   #:+max+
   #:+blend-equation+
   #:+blend-equation-rgb+
   #:+blend-equation-alpha+
   #:+func-subtract+
   #:+func-reverse-subtract+
   #:+color-matrix+
   #:+color-matrix-stack-depth+
   #:+max-color-matrix-stack-depth+
   #:+post-color-matrix-red-scale+
   #:+post-color-matrix-green-scale+
   #:+post-color-matrix-blue-scale+
   #:+post-color-matrix-alpha-scale+
   #:+post-color-matrix-red-bias+
   #:+post-color-matrix-green-bias+
   #:+post-color-matrix-blue-bias+
   #:+post-color-matrix-alpha-bias+
   #:+color-table+
   #:+post-convolution-color-table+
   #:+post-color-matrix-color-table+
   #:+proxy-color-table+
   #:+proxy-post-convolution-color-table+
   #:+proxy-post-color-matrix-color-table+
   #:+color-table-scale+
   #:+color-table-bias+
   #:+color-table-format+
   #:+color-table-width+
   #:+color-table-red-size+
   #:+color-table-green-size+
   #:+color-table-blue-size+
   #:+color-table-alpha-size+
   #:+color-table-luminance-size+
   #:+color-table-intensity-size+
   #:+convolution-1d+
   #:+convolution-2d+
   #:+separable-2d+
   #:+convolution-border-mode+
   #:+convolution-filter-scale+
   #:+convolution-filter-bias+
   #:+reduce+
   #:+convolution-format+
   #:+convolution-width+
   #:+convolution-height+
   #:+max-convolution-width+
   #:+max-convolution-height+
   #:+post-convolution-red-scale+
   #:+post-convolution-green-scale+
   #:+post-convolution-blue-scale+
   #:+post-convolution-alpha-scale+
   #:+post-convolution-red-bias+
   #:+post-convolution-green-bias+
   #:+post-convolution-blue-bias+
   #:+post-convolution-alpha-bias+
   #:+constant-border+
   #:+replicate-border+
   #:+convolution-border-color+
   #:+max-elements-vertices+
   #:+max-elements-indices+
   #:+histogram+
   #:+proxy-histogram+
   #:+histogram-width+
   #:+histogram-format+
   #:+histogram-red-size+
   #:+histogram-green-size+
   #:+histogram-blue-size+
   #:+histogram-alpha-size+
   #:+histogram-luminance-size+
   #:+histogram-sink+
   #:+minmax+
   #:+minmax-format+
   #:+minmax-sink+
   #:+table-too-large+
   #:+unsigned-byte-3-3-2+
   #:+unsigned-short-4-4-4-4+
   #:+unsigned-short-5-5-5-1+
   #:+unsigned-int-8-8-8-8+
   #:+unsigned-int-10-10-10-2+
   #:+unsigned-byte-2-3-3-rev+
   #:+unsigned-short-5-6-5+
   #:+unsigned-short-5-6-5-rev+
   #:+unsigned-short-4-4-4-4-rev+
   #:+unsigned-short-1-5-5-5-rev+
   #:+unsigned-int-8-8-8-8-rev+
   #:+unsigned-int-2-10-10-10-rev+
   #:+rescale-normal+
   #:+light-model-color-control+
   #:+single-color+
   #:+separate-specular-color+
   #:+pack-skip-images+
   #:+pack-image-height+
   #:+unpack-skip-images+
   #:+unpack-image-height+
   #:+texture-3d+
   #:+proxy-texture-3d+
   #:+texture-depth+
   #:+texture-wrap-r+
   #:+max-3d-texture-size+
   #:+clamp-to-edge+
   #:+clamp-to-border+
   #:+texture-min-lod+
   #:+texture-max-lod+
   #:+texture-base-level+
   #:+texture-max-level+
   #:+smooth-point-size-range+
   #:+smooth-point-size-granularity+
   #:+smooth-line-width-range+
   #:+smooth-line-width-granularity+
   #:+aliased-point-size-range+
   #:+aliased-line-width-range+
   #:+texture0+
   #:+texture1+
   #:+texture2+
   #:+texture3+
   #:+texture4+
   #:+texture5+
   #:+texture6+
   #:+texture7+
   #:+texture8+
   #:+texture9+
   #:+texture10+
   #:+texture11+
   #:+texture12+
   #:+texture13+
   #:+texture14+
   #:+texture15+
   #:+texture16+
   #:+texture17+
   #:+texture18+
   #:+texture19+
   #:+texture20+
   #:+texture21+
   #:+texture22+
   #:+texture23+
   #:+texture24+
   #:+texture25+
   #:+texture26+
   #:+texture27+
   #:+texture28+
   #:+texture29+
   #:+texture30+
   #:+texture31+
   #:+active-texture+
   #:+client-active-texture+
   #:+max-texture-units+
   #:+combine+
   #:+combine-rgb+
   #:+combine-alpha+
   #:+rgb-scale+
   #:+add-signed+
   #:+interpolate+
   #:+constant+
   #:+primary-color+
   #:+previous+
   #:+subtract+
   #:+src0-rgb+
   #:+src1-rgb+
   #:+src2-rgb+
   #:+src3-rgb+
   #:+src4-rgb+
   #:+src5-rgb+
   #:+src6-rgb+
   #:+src7-rgb+
   #:+src0-alpha+
   #:+src1-alpha+
   #:+src2-alpha+
   #:+src3-alpha+
   #:+src4-alpha+
   #:+src5-alpha+
   #:+src6-alpha+
   #:+src7-alpha+
   #:+source0-rgb+
   #:+source1-rgb+
   #:+source2-rgb+
   #:+source3-rgb+
   #:+source4-rgb+
   #:+source5-rgb+
   #:+source6-rgb+
   #:+source7-rgb+
   #:+source0-alpha+
   #:+source1-alpha+
   #:+source2-alpha+
   #:+source3-alpha+
   #:+source4-alpha+
   #:+source5-alpha+
   #:+source6-alpha+
   #:+source7-alpha+
   #:+operand0-rgb+
   #:+operand1-rgb+
   #:+operand2-rgb+
   #:+operand3-rgb+
   #:+operand4-rgb+
   #:+operand5-rgb+
   #:+operand6-rgb+
   #:+operand7-rgb+
   #:+operand0-alpha+
   #:+operand1-alpha+
   #:+operand2-alpha+
   #:+operand3-alpha+
   #:+operand4-alpha+
   #:+operand5-alpha+
   #:+operand6-alpha+
   #:+operand7-alpha+
   #:+dot3-rgb+
   #:+dot3-rgba+
   #:+transpose-modelview-matrix+
   #:+transpose-projection-matrix+
   #:+transpose-texture-matrix+
   #:+transpose-color-matrix+
   #:+normal-map+
   #:+reflection-map+
   #:+texture-cube-map+
   #:+texture-binding-cube-map+
   #:+texture-cube-map-positive-x+
   #:+texture-cube-map-negative-x+
   #:+texture-cube-map-positive-y+
   #:+texture-cube-map-negative-y+
   #:+texture-cube-map-positive-z+
   #:+texture-cube-map-negative-z+
   #:+proxy-texture-cube-map+
   #:+max-cube-map-texture-size+
   #:+compressed-alpha+
   #:+compressed-luminance+
   #:+compressed-luminance-alpha+
   #:+compressed-intensity+
   #:+compressed-rgb+
   #:+compressed-rgba+
   #:+texture-compression-hint+
   #:+texture-compressed-image-size+
   #:+texture-compressed+
   #:+num-compressed-texture-formats+
   #:+compressed-texture-formats+
   #:+multisample+
   #:+sample-alpha-to-coverage+
   #:+sample-alpha-to-one+
   #:+sample-coverage+
   #:+sample-buffers+
   #:+samples+
   #:+sample-coverage-value+
   #:+sample-coverage-invert+
   #:+multisample-bit+
   #:+depth-component16+
   #:+depth-component24+
   #:+depth-component32+
   #:+texture-depth-size+
   #:+depth-texture-mode+
   #:+texture-compare-mode+
   #:+texture-compare-func+
   #:+compare-r-to-texture+
   #:+query-counter-bits+
   #:+current-query+
   #:+query-result+
   #:+query-result-available+
   #:+samples-passed+
   #:+fog-coord-src+
   #:+fog-coord+
   #:+fragment-depth+
   #:+current-fog-coord+
   #:+fog-coord-array-type+
   #:+fog-coord-array-stride+
   #:+fog-coord-array-pointer+
   #:+fog-coord-array+
   #:+fog-coordinate-source+
   #:+fog-coordinate+
   #:+current-fog-coordinate+
   #:+fog-coordinate-array-type+
   #:+fog-coordinate-array-stride+
   #:+fog-coordinate-array-pointer+
   #:+fog-coordinate-array+
   #:+color-sum+
   #:+current-secondary-color+
   #:+secondary-color-array-size+
   #:+secondary-color-array-type+
   #:+secondary-color-array-stride+
   #:+secondary-color-array-pointer+
   #:+secondary-color-array+
   #:+point-size-min+
   #:+point-size-max+
   #:+point-fade-threshold-size+
   #:+point-distance-attenuation+
   #:+blend-dst-rgb+
   #:+blend-src-rgb+
   #:+blend-dst-alpha+
   #:+blend-src-alpha+
   #:+generate-mipmap+
   #:+generate-mipmap-hint+
   #:+incr-wrap+
   #:+decr-wrap+
   #:+mirrored-repeat+
   #:+max-texture-lod-bias+
   #:+texture-filter-control+
   #:+texture-lod-bias+
   #:+array-buffer+
   #:+element-array-buffer+
   #:+array-buffer-binding+
   #:+element-array-buffer-binding+
   #:+vertex-array-buffer-binding+
   #:+normal-array-buffer-binding+
   #:+color-array-buffer-binding+
   #:+index-array-buffer-binding+
   #:+texture-coord-array-buffer-binding+
   #:+edge-flag-array-buffer-binding+
   #:+secondary-color-array-buffer-binding+
   #:+fog-coord-array-buffer-binding+
   #:+weight-array-buffer-binding+
   #:+vertex-attrib-array-buffer-binding+
   #:+stream-draw+
   #:+stream-read+
   #:+stream-copy+
   #:+static-draw+
   #:+static-read+
   #:+static-copy+
   #:+dynamic-draw+
   #:+dynamic-read+
   #:+dynamic-copy+
   #:+read-only+
   #:+write-only+
   #:+read-write+
   #:+buffer-size+
   #:+buffer-usage+
   #:+buffer-access+
   #:+buffer-mapped+
   #:+buffer-map-pointer+
   #:+fog-coordinate-array-buffer-binding+
   #:+current-program+
   #:+shader-type+
   #:+delete-status+
   #:+compile-status+
   #:+link-status+
   #:+validate-status+
   #:+info-log-length+
   #:+attached-shaders+
   #:+active-uniforms+
   #:+active-uniform-max-length+
   #:+shader-source-length+
   #:+float-vec2+
   #:+float-vec3+
   #:+float-vec4+
   #:+int-vec2+
   #:+int-vec3+
   #:+int-vec4+
   #:+bool+
   #:+bool-vec2+
   #:+bool-vec3+
   #:+bool-vec4+
   #:+float-mat2+
   #:+float-mat3+
   #:+float-mat4+
   #:+sampler-1d+
   #:+sampler-2d+
   #:+sampler-3d+
   #:+sampler-cube+
   #:+sampler-1d-shadow+
   #:+sampler-2d-shadow+
   #:+shading-language-version+
   #:+vertex-shader+
   #:+max-vertex-uniform-components+
   #:+max-varying-floats+
   #:+max-vertex-texture-image-units+
   #:+max-combined-texture-image-units+
   #:+active-attributes+
   #:+active-attribute-max-length+
   #:+fragment-shader+
   #:+max-fragment-uniform-components+
   #:+fragment-shader-derivative-hint+
   #:+max-vertex-attribs+
   #:+vertex-attrib-array-enabled+
   #:+vertex-attrib-array-size+
   #:+vertex-attrib-array-stride+
   #:+vertex-attrib-array-type+
   #:+vertex-attrib-array-normalized+
   #:+current-vertex-attrib+
   #:+vertex-attrib-array-pointer+
   #:+vertex-program-point-size+
   #:+vertex-program-two-side+
   #:+max-texture-coords+
   #:+max-texture-image-units+
   #:+max-draw-buffers+
   #:+draw-buffer0+
   #:+draw-buffer1+
   #:+draw-buffer2+
   #:+draw-buffer3+
   #:+draw-buffer4+
   #:+draw-buffer5+
   #:+draw-buffer6+
   #:+draw-buffer7+
   #:+draw-buffer8+
   #:+draw-buffer9+
   #:+draw-buffer10+
   #:+draw-buffer11+
   #:+draw-buffer12+
   #:+draw-buffer13+
   #:+draw-buffer14+
   #:+draw-buffer15+
   #:+point-sprite+
   #:+coord-replace+
   #:+point-sprite-coord-origin+
   #:+lower-left+
   #:+upper-left+
   #:+stencil-back-func+
   #:+stencil-back-value-mask+
   #:+stencil-back-ref+
   #:+stencil-back-fail+
   #:+stencil-back-pass-depth-fail+
   #:+stencil-back-pass-depth-pass+
   #:+stencil-back-writemask+
   #:+current-raster-secondary-color+
   #:+pixel-pack-buffer+
   #:+pixel-unpack-buffer+
   #:+pixel-pack-buffer-binding+
   #:+pixel-unpack-buffer-binding+
   #:+float-mat2x3+
   #:+float-mat2x4+
   #:+float-mat3x2+
   #:+float-mat3x4+
   #:+float-mat4x2+
   #:+float-mat4x3+
   #:+srgb+
   #:+srgb8+
   #:+srgb-alpha+
   #:+srgb8-alpha8+
   #:+sluminance-alpha+
   #:+sluminance8-alpha8+
   #:+sluminance+
   #:+sluminance8+
   #:+compressed-srgb+
   #:+compressed-srgb-alpha+
   #:+compressed-sluminance+
   #:+compressed-sluminance-alpha+
   #:push-pop-matrix
   #:push-pop-attribute
   #:disable-block
   #:enable-block
   #:clear-color-fv
   #:clear-color-dv
   #:vertex-3fv
   #:vertex-3dv
   #:translate-fv
   #:translate-dv
   #:normal-3fv
   #:normal-3dv
   #:command
   #:light-fv
   #:material-fv
   #:mult-matrix-f
   #:mult-matrix-d
   #:color-3fv
   #:color-3dv
   #:tex-coord-2fv
   #:tex-coord-2dv
   #:new-texture-name
   #:display-list-block
   )
  )

(defpackage :glx
  (:use #:common-lisp #:cffi  #:chimi)
  (:export
   #:choose-visual
   #:create-context
   #:make-current
   #:get-current-drawable
   #:get-current-context
   #:swap-buffers
   #:+USE-GL+
   #:+BUFFER-SIZE+
   #:+LEVEL+
   #:+RGBA+
   #:+DOUBLEBUFFER+
   #:+STEREO+
   #:+AUX-BUFFERS+
   #:+RED-SIZE+
   #:+GREEN-SIZE+
   #:+BLUE-SIZE+
   #:+ALPHA-SIZE+
   #:+DEPTH-SIZE+
   #:+STENCIL-SIZE+
   #:+ACCUM-RED-SIZE+
   #:+ACCUM-GREEN-SIZE+
   #:+ACCUM-BLUE-SIZE+
   #:+ACCUM-ALPHA-SIZE+
   #:+multisample+
   )
  )

(defpackage :glu
  (:use #:common-lisp #:cffi  #:chimi)
  (:export
   #:perspective
   #:look-at
   )
  )
